name: Deploy

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        env:
          HOST: ${{ secrets.HOST }}
          PATH: ${{ vars.TEST_PATH }}
        with:
          host: $HOST
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: PATH
          script: cd $PATH
            && git reset --hard
            && git pull
            && php -v
            && composer update --ignore-platform-req=ext-http --ignore-platform-req=ext-dom --ignore-platform-req=ext-simplexml
            && php artisan key:generate
            && php artisan migrate
            && php artisan optimize
            && php artisan cache:clear
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: $HOST
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: PATH
          script: cd $PATH
            && cp deploy/queue-worker.conf /etc/supervisor/conf.d
            && cp deploy/schedule-worker.conf /etc/supervisor/conf.d
            && supervisorctl reread
            && service supervisor restart


