name: Deploy

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /var/www/altertravel.ru/data/www/api.altertravel.ru
            && git reset --hard
            && git pull
            && cp deploy/queue-worker.conf /etc/supervisor/conf.d
            && cp deploy/schedule-worker.conf /etc/supervisor/conf.d
            && su altertravel.ru
            && /opt/php81/bin/php /usr/local/bin/composer self-update 2.2
            && /opt/php81/bin/php /usr/local/bin/composer update --ignore-platform-req=ext-http --ignore-platform-req=ext-dom --ignore-platform-req=ext-simplexml
            && php artisan key:generate
            && php artisan migrate
            && php artisan optimize
            && php artisan cache:clear
            && supervisorctl reread
            && service supervisor restart


