name: Deploy

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /var/www/altertravel.ru/data/www/api.altertravel.ru
            && git stash push --include-untracked
            && git stash drop
            && git pull
            && su altertravel.ru
            && composer update --ignore-platform-req=ext-http --ignore-platform-req=ext-dom
            && php artisan migrate
            && php artisan optimize
            && php artisan fill:url


