name: Deploy

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: cd ${{ vars.TEST_PATH }}
            && su altertravel.ru
            && git reset --hard
            && git pull
            && php artisan key:generate
            && php artisan migrate
            && php artisan optimize
            && php artisan cache:clear
            && cp deploy/queue-worker.conf /etc/supervisor/conf.d
            && cp deploy/schedule-worker.conf /etc/supervisor/conf.d
            && supervisorctl reread
            && service supervisor restart
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          port: 22
          script: cd ${{ vars.TEST_PATH }}
            && php -v
            && composer update --ignore-platform-req=ext-http --ignore-platform-req=ext-dom --ignore-platform-req=ext-simplexml




